spring.application.name=spring-boot-rest
spring.datasource.url=jdbc:postgresql://localhost:5432/spring-boot-jpa
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

#Spring using hibernate behind the scenes to execute query, and below property will create table or any column if doesn't exist or simply update.
spring.jpa.hibernate.ddl-auto=update
#Below will show the query it fires behind the scene to complete the request.
spring.jpa.show-sql=true
